version: '3'

services:
  # Cliente Vue.js
  client:
    build:
      #context: ./ProjectSchoolStudent-Front-end
      dockerfile: DockerfileFrontend
    ports:
      - "80:80"
    depends_on:
      - api

  # API Laravel
  api:
    build:
      #context: ./ProjectSchoolStudent-Back-end
      dockerfile: DockerfileBackend
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80 || exit 1"]
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    command: ["sh", "-c", "apache2-foreground"]
